lokoctl:
  branch: master

charts:
  branch: master

terraform:
  version: 0.13.6

helm:
  version: 3.5.1

sshKey:
  public:
  private:

# Possible values: [equinix-metal, aws].
benchmarkingClusterCloud:

# This is to be set using the helm flag `--set-file`.
runScript:

clouds:
  aws:
    accessKeyID:
    secretAccessKey:
    defaultRegion: eu-central-1
    route53Zone:
    route53ZoneID:

  packet:
    token:
    projectID:
    regionEIPs:
