apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-install-configs
  namespace: {{.Release.Namespace}}
data:
{{ if eq .Values.benchmarkingClusterCloud "equinix-metal" }}
{{ (.Files.Glob "cluster-install-configs/equinix-metal/equinix-metal.lokocfg").AsConfig | indent 2 }}
{{ (.Files.Glob "cluster-install-configs/equinix-metal/equinix-metal.vars.envsubst").AsConfig | indent 2 }}
{{ else if eq .Values.benchmarkingClusterCloud "aws" }}
{{ (.Files.Glob "cluster-install-configs/aws/aws.lokocfg").AsConfig | indent 2 }}
{{ (.Files.Glob "cluster-install-configs/aws/aws.vars.envsubst").AsConfig | indent 2 }}
{{ else if eq .Values.benchmarkingClusterCloud "oci" }}
{{ (.Files.Glob "cluster-install-configs/oci/oci.lokocfg").AsConfig | indent 2 }}
{{ (.Files.Glob "cluster-install-configs/oci/oci.vars.envsubst").AsConfig | indent 2 }}
{{ end }}
{{ (.Files.Glob "cluster-install-configs/cleanup.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "cluster-install-configs/cleanup-setup.sh").AsConfig | indent 2 }}
  run.sh: |
{{ .Values.runScript | indent 4 }}
