apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orchestrator
  name: orchestrator
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
        pvc: binaries
    spec:
      containers:
      - image: quay.io/kinvolk/smb-orchestrator
        name: orchestrator
        env:
        {{ if .Values.clouds.em.regionEIPs -}}
        - name: REGION_EIPS
          value: {{.Values.clouds.em.regionEIPs}}
        {{ end -}}
        - name: AWS_REGIONS
          value: {{.Values.clouds.aws.regions}}
        {{ if .Values.clouds.oci.region -}}
        - name: OCI_REGION
          value: {{.Values.clouds.oci.region}}
        {{ end -}}
        - name: BENCHMARKING_CLUSTER_CLOUD
          value: {{.Values.benchmarkingClusterCloud}}
        - name: OC_NAMESPACE
          value: {{.Release.Namespace}}
        volumeMounts:
        - name: binaries
          mountPath: /binaries
        - name: cluster-install-configs
          mountPath: /scripts
      serviceAccountName: orchestrator
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: pvc
                operator: In
                values:
                - binaries
            topologyKey: kubernetes.io/hostname
      volumes:
      - name: binaries
        persistentVolumeClaim:
          claimName: binaries
      - name: cluster-install-configs
        configMap:
          name: cluster-install-configs
